; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu -mcpu=haswell < %s | FileCheck %s

; Keep the related affine addresses scalar so loop strength reduction can
; replace the index arithmetic with pointer increments.

define i32 @strided_gather(ptr %base, ptr %dims, i64 %n) {
; CHECK-LABEL: define i32 @strided_gather(
; CHECK-SAME: ptr [[BASE:%.*]], ptr [[DIMS:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[STRIDE:%.*]] = load i64, ptr [[DIMS]], align 8
; CHECK-NEXT:    [[OFF_PTR:%.*]] = getelementptr i8, ptr [[DIMS]], i64 8
; CHECK-NEXT:    [[OFF:%.*]] = load i64, ptr [[OFF_PTR]], align 8
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I1:%.*]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[I2:%.*]] = add i64 [[IV]], 2
; CHECK-NEXT:    [[I3:%.*]] = add i64 [[IV]], 3
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 4
; CHECK-NEXT:    [[M0:%.*]] = mul i64 [[STRIDE]], [[I1]]
; CHECK-NEXT:    [[M1:%.*]] = mul i64 [[STRIDE]], [[I2]]
; CHECK-NEXT:    [[M2:%.*]] = mul i64 [[STRIDE]], [[I3]]
; CHECK-NEXT:    [[M3:%.*]] = mul i64 [[STRIDE]], [[IV_NEXT]]
; CHECK-NEXT:    [[A0:%.*]] = add i64 [[OFF]], [[M0]]
; CHECK-NEXT:    [[A1:%.*]] = add i64 [[OFF]], [[M1]]
; CHECK-NEXT:    [[A2:%.*]] = add i64 [[OFF]], [[M2]]
; CHECK-NEXT:    [[A3:%.*]] = add i64 [[OFF]], [[M3]]
; CHECK-NEXT:    [[S0:%.*]] = shl i64 [[A0]], 2
; CHECK-NEXT:    [[S1:%.*]] = shl i64 [[A1]], 2
; CHECK-NEXT:    [[S2:%.*]] = shl i64 [[A2]], 2
; CHECK-NEXT:    [[S3:%.*]] = shl i64 [[A3]], 2
; CHECK-NEXT:    [[P0:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[S0]]
; CHECK-NEXT:    [[P1:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[S1]]
; CHECK-NEXT:    [[P2:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[S2]]
; CHECK-NEXT:    [[P3:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[S3]]
; CHECK-NEXT:    [[L0:%.*]] = load i32, ptr [[P0]], align 4
; CHECK-NEXT:    [[L1:%.*]] = load i32, ptr [[P1]], align 4
; CHECK-NEXT:    [[L2:%.*]] = load i32, ptr [[P2]], align 4
; CHECK-NEXT:    [[L3:%.*]] = load i32, ptr [[P3]], align 4
; CHECK-NEXT:    [[V0:%.*]] = insertelement <4 x i32> poison, i32 [[L0]], i64 0
; CHECK-NEXT:    [[V1:%.*]] = insertelement <4 x i32> [[V0]], i32 [[L1]], i64 1
; CHECK-NEXT:    [[V2:%.*]] = insertelement <4 x i32> [[V1]], i32 [[L2]], i64 2
; CHECK-NEXT:    [[V3:%.*]] = insertelement <4 x i32> [[V2]], i32 [[L3]], i64 3
; CHECK-NEXT:    [[R:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[V3]])
; CHECK-NEXT:    [[ACC_NEXT]] = add i32 [[ACC]], [[R]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[ACC_NEXT]]
;
entry:
  %stride = load i64, ptr %dims, align 8
  %off.ptr = getelementptr i8, ptr %dims, i64 8
  %off = load i64, ptr %off.ptr, align 8
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %i1 = add i64 %iv, 1
  %i2 = add i64 %iv, 2
  %i3 = add i64 %iv, 3
  %iv.next = add i64 %iv, 4
  %m0 = mul i64 %stride, %i1
  %m1 = mul i64 %stride, %i2
  %m2 = mul i64 %stride, %i3
  %m3 = mul i64 %stride, %iv.next
  %a0 = add i64 %off, %m0
  %a1 = add i64 %off, %m1
  %a2 = add i64 %off, %m2
  %a3 = add i64 %off, %m3
  %s0 = shl i64 %a0, 2
  %s1 = shl i64 %a1, 2
  %s2 = shl i64 %a2, 2
  %s3 = shl i64 %a3, 2
  %p0 = getelementptr i8, ptr %base, i64 %s0
  %p1 = getelementptr i8, ptr %base, i64 %s1
  %p2 = getelementptr i8, ptr %base, i64 %s2
  %p3 = getelementptr i8, ptr %base, i64 %s3
  %l0 = load i32, ptr %p0, align 4
  %l1 = load i32, ptr %p1, align 4
  %l2 = load i32, ptr %p2, align 4
  %l3 = load i32, ptr %p3, align 4
  %v0 = insertelement <4 x i32> poison, i32 %l0, i64 0
  %v1 = insertelement <4 x i32> %v0, i32 %l1, i64 1
  %v2 = insertelement <4 x i32> %v1, i32 %l2, i64 2
  %v3 = insertelement <4 x i32> %v2, i32 %l3, i64 3
  %r = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> %v3)
  %acc.next = add i32 %acc, %r
  %done = icmp eq i64 %iv.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; Constant-offset GEPs between the addresses and loads do not prevent this.

define i32 @strided_gather_offset(ptr %base, ptr %dims, i64 %n) {
; CHECK-LABEL: define i32 @strided_gather_offset(
; CHECK-SAME: ptr [[BASE:%.*]], ptr [[DIMS:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[STRIDE:%.*]] = load i64, ptr [[DIMS]], align 8
; CHECK-NEXT:    [[OFF_PTR:%.*]] = getelementptr i8, ptr [[DIMS]], i64 8
; CHECK-NEXT:    [[OFF:%.*]] = load i64, ptr [[OFF_PTR]], align 8
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I1:%.*]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[I2:%.*]] = add i64 [[IV]], 2
; CHECK-NEXT:    [[I3:%.*]] = add i64 [[IV]], 3
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 4
; CHECK-NEXT:    [[M0:%.*]] = mul i64 [[STRIDE]], [[I1]]
; CHECK-NEXT:    [[M1:%.*]] = mul i64 [[STRIDE]], [[I2]]
; CHECK-NEXT:    [[M2:%.*]] = mul i64 [[STRIDE]], [[I3]]
; CHECK-NEXT:    [[M3:%.*]] = mul i64 [[STRIDE]], [[IV_NEXT]]
; CHECK-NEXT:    [[A0:%.*]] = add i64 [[OFF]], [[M0]]
; CHECK-NEXT:    [[A1:%.*]] = add i64 [[OFF]], [[M1]]
; CHECK-NEXT:    [[A2:%.*]] = add i64 [[OFF]], [[M2]]
; CHECK-NEXT:    [[A3:%.*]] = add i64 [[OFF]], [[M3]]
; CHECK-NEXT:    [[S0:%.*]] = shl i64 [[A0]], 2
; CHECK-NEXT:    [[S1:%.*]] = shl i64 [[A1]], 2
; CHECK-NEXT:    [[S2:%.*]] = shl i64 [[A2]], 2
; CHECK-NEXT:    [[S3:%.*]] = shl i64 [[A3]], 2
; CHECK-NEXT:    [[P0:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[S0]]
; CHECK-NEXT:    [[P1:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[S1]]
; CHECK-NEXT:    [[P2:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[S2]]
; CHECK-NEXT:    [[P3:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[S3]]
; CHECK-NEXT:    [[Q0:%.*]] = getelementptr i8, ptr [[P0]], i64 -4
; CHECK-NEXT:    [[L0:%.*]] = load i32, ptr [[Q0]], align 4
; CHECK-NEXT:    [[Q1:%.*]] = getelementptr i8, ptr [[P1]], i64 -4
; CHECK-NEXT:    [[L1:%.*]] = load i32, ptr [[Q1]], align 4
; CHECK-NEXT:    [[Q2:%.*]] = getelementptr i8, ptr [[P2]], i64 -4
; CHECK-NEXT:    [[L2:%.*]] = load i32, ptr [[Q2]], align 4
; CHECK-NEXT:    [[Q3:%.*]] = getelementptr i8, ptr [[P3]], i64 -4
; CHECK-NEXT:    [[L3:%.*]] = load i32, ptr [[Q3]], align 4
; CHECK-NEXT:    [[V0:%.*]] = insertelement <4 x i32> poison, i32 [[L0]], i64 0
; CHECK-NEXT:    [[V1:%.*]] = insertelement <4 x i32> [[V0]], i32 [[L1]], i64 1
; CHECK-NEXT:    [[V2:%.*]] = insertelement <4 x i32> [[V1]], i32 [[L2]], i64 2
; CHECK-NEXT:    [[V3:%.*]] = insertelement <4 x i32> [[V2]], i32 [[L3]], i64 3
; CHECK-NEXT:    [[R:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[V3]])
; CHECK-NEXT:    [[ACC_NEXT]] = add i32 [[ACC]], [[R]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[ACC_NEXT]]
;
entry:
  %stride = load i64, ptr %dims, align 8
  %off.ptr = getelementptr i8, ptr %dims, i64 8
  %off = load i64, ptr %off.ptr, align 8
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %i1 = add i64 %iv, 1
  %i2 = add i64 %iv, 2
  %i3 = add i64 %iv, 3
  %iv.next = add i64 %iv, 4
  %m0 = mul i64 %stride, %i1
  %m1 = mul i64 %stride, %i2
  %m2 = mul i64 %stride, %i3
  %m3 = mul i64 %stride, %iv.next
  %a0 = add i64 %off, %m0
  %a1 = add i64 %off, %m1
  %a2 = add i64 %off, %m2
  %a3 = add i64 %off, %m3
  %s0 = shl i64 %a0, 2
  %s1 = shl i64 %a1, 2
  %s2 = shl i64 %a2, 2
  %s3 = shl i64 %a3, 2
  %p0 = getelementptr i8, ptr %base, i64 %s0
  %p1 = getelementptr i8, ptr %base, i64 %s1
  %p2 = getelementptr i8, ptr %base, i64 %s2
  %p3 = getelementptr i8, ptr %base, i64 %s3
  %q0 = getelementptr i8, ptr %p0, i64 -4
  %l0 = load i32, ptr %q0, align 4
  %q1 = getelementptr i8, ptr %p1, i64 -4
  %l1 = load i32, ptr %q1, align 4
  %q2 = getelementptr i8, ptr %p2, i64 -4
  %l2 = load i32, ptr %q2, align 4
  %q3 = getelementptr i8, ptr %p3, i64 -4
  %l3 = load i32, ptr %q3, align 4
  %v0 = insertelement <4 x i32> poison, i32 %l0, i64 0
  %v1 = insertelement <4 x i32> %v0, i32 %l1, i64 1
  %v2 = insertelement <4 x i32> %v1, i32 %l2, i64 2
  %v3 = insertelement <4 x i32> %v2, i32 %l3, i64 3
  %r = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> %v3)
  %acc.next = add i32 %acc, %r
  %done = icmp eq i64 %iv.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; The offset is loaded in the loop, so the addresses are not recurrences of
; the loop and the index computation is vectorized as before.

define i32 @variant_offset(ptr %base, ptr %dims, i64 %n) {
; CHECK-LABEL: define i32 @variant_offset(
; CHECK-SAME: ptr [[BASE:%.*]], ptr [[DIMS:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[STRIDE:%.*]] = load i64, ptr [[DIMS]], align 8
; CHECK-NEXT:    [[OFF_PTR:%.*]] = getelementptr i8, ptr [[DIMS]], i64 8
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i64> poison, i64 [[STRIDE]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i64> [[TMP0]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[OFF:%.*]] = load i64, ptr [[OFF_PTR]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x i64> poison, i64 [[IV]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i64> [[TMP2]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = add <4 x i64> [[TMP3]], <i64 1, i64 2, i64 3, i64 4>
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = mul <4 x i64> [[TMP1]], [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x i64> poison, i64 [[OFF]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <4 x i64> [[TMP6]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = add <4 x i64> [[TMP7]], [[TMP5]]
; CHECK-NEXT:    [[TMP9:%.*]] = shl <4 x i64> [[TMP8]], splat (i64 2)
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x i64> [[TMP9]], i64 0
; CHECK-NEXT:    [[P0:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[TMP10]]
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <4 x i64> [[TMP9]], i64 1
; CHECK-NEXT:    [[P1:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[TMP11]]
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <4 x i64> [[TMP9]], i64 2
; CHECK-NEXT:    [[P2:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[TMP12]]
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <4 x i64> [[TMP9]], i64 3
; CHECK-NEXT:    [[P3:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[TMP13]]
; CHECK-NEXT:    [[L0:%.*]] = load i32, ptr [[P0]], align 4
; CHECK-NEXT:    [[L1:%.*]] = load i32, ptr [[P1]], align 4
; CHECK-NEXT:    [[L2:%.*]] = load i32, ptr [[P2]], align 4
; CHECK-NEXT:    [[L3:%.*]] = load i32, ptr [[P3]], align 4
; CHECK-NEXT:    [[V0:%.*]] = insertelement <4 x i32> poison, i32 [[L0]], i64 0
; CHECK-NEXT:    [[V1:%.*]] = insertelement <4 x i32> [[V0]], i32 [[L1]], i64 1
; CHECK-NEXT:    [[V2:%.*]] = insertelement <4 x i32> [[V1]], i32 [[L2]], i64 2
; CHECK-NEXT:    [[V3:%.*]] = insertelement <4 x i32> [[V2]], i32 [[L3]], i64 3
; CHECK-NEXT:    [[R:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[V3]])
; CHECK-NEXT:    [[ACC_NEXT]] = add i32 [[ACC]], [[R]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[ACC_NEXT]]
;
entry:
  %stride = load i64, ptr %dims, align 8
  %off.ptr = getelementptr i8, ptr %dims, i64 8

  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %off = load i64, ptr %off.ptr, align 8
  %i1 = add i64 %iv, 1
  %i2 = add i64 %iv, 2
  %i3 = add i64 %iv, 3
  %iv.next = add i64 %iv, 4
  %m0 = mul i64 %stride, %i1
  %m1 = mul i64 %stride, %i2
  %m2 = mul i64 %stride, %i3
  %m3 = mul i64 %stride, %iv.next
  %a0 = add i64 %off, %m0
  %a1 = add i64 %off, %m1
  %a2 = add i64 %off, %m2
  %a3 = add i64 %off, %m3
  %s0 = shl i64 %a0, 2
  %s1 = shl i64 %a1, 2
  %s2 = shl i64 %a2, 2
  %s3 = shl i64 %a3, 2
  %p0 = getelementptr i8, ptr %base, i64 %s0
  %p1 = getelementptr i8, ptr %base, i64 %s1
  %p2 = getelementptr i8, ptr %base, i64 %s2
  %p3 = getelementptr i8, ptr %base, i64 %s3
  %l0 = load i32, ptr %p0, align 4
  %l1 = load i32, ptr %p1, align 4
  %l2 = load i32, ptr %p2, align 4
  %l3 = load i32, ptr %p3, align 4
  %v0 = insertelement <4 x i32> poison, i32 %l0, i64 0
  %v1 = insertelement <4 x i32> %v0, i32 %l1, i64 1
  %v2 = insertelement <4 x i32> %v1, i32 %l2, i64 2
  %v3 = insertelement <4 x i32> %v2, i32 %l3, i64 3
  %r = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> %v3)
  %acc.next = add i32 %acc, %r
  %done = icmp eq i64 %iv.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}
