; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -opaque-pointers -mtriple=powerpc64le-unknown-unknown < %s | FileCheck %s
; RUN: llc -opaque-pointers -mtriple=powerpc64-unknown-unknown < %s | FileCheck %s

define void @foo() #0 {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %bb0
; CHECK-NEXT:    bc 12, 20, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %bb1
; CHECK-NEXT:    ld 3, 0(3)
; CHECK-NEXT:    cmpd 7, 3, 3
; CHECK-NEXT:    bne- 7, .+4
; CHECK-NEXT:    isync
; CHECK-NEXT:  .LBB0_2: # %bb2
bb0:
  br i1 undef, label %bb1, label %bb2

bb1:
  %0 = load atomic {}*, {}** undef acquire, align 8
  unreachable

bb2:
  unreachable
}

define void @bar() #0 {
; CHECK-LABEL: bar:
; CHECK:       # %bb.0: # %bb0
; CHECK-NEXT:    bc 12, 20, .LBB1_2
; CHECK-NEXT:  # %bb.1: # %bb1
; CHECK-NEXT:    ld 3, 0(3)
; CHECK-NEXT:    cmpd 7, 3, 3
; CHECK-NEXT:    bne- 7, .+4
; CHECK-NEXT:    isync
; CHECK-NEXT:  .LBB1_2: # %bb2
bb0:
  br i1 undef, label %bb1, label %bb2

bb1:
  %0 = load atomic ptr, ptr undef acquire, align 8
  unreachable

bb2:
  unreachable
}

define void @foobar() {
; CHECK-LABEL: foobar:
; CHECK:       # %bb.0: # %top
; CHECK-NEXT:    bc 4, 20, .LBB2_2
; CHECK-NEXT:  # %bb.1: # %err86
; CHECK-NEXT:  .LBB2_2: # %pass9
; CHECK-NEXT:    ld 3, 0(3)
; CHECK-NEXT:    cmpd 7, 3, 3
; CHECK-NEXT:    bne- 7, .+4
; CHECK-NEXT:    isync
top:
  br i1 undef, label %err86, label %pass9

pass9:                                            ; preds = %top
  %0 = load atomic {} addrspace(10)*, {} addrspace(10)* addrspace(11)* undef acquire, align 8
  unreachable

err86:                                            ; preds = %top
  unreachable
}
